baseURL = "https://nolwenndeumie.github.io/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Révisions LLCE"
theme = "hugo-royal-theme"

[social]
twitter = "iWannaSlytherIn"

[[menu.global]]
name = "Twitter"
weight = 1
identifier = "twitter"
url = "https://twitter.com/IWannaSlytherIn"

[[menu.global]]
name = "Faire un don"
weight = 2
identifier = "don"
url = "https://paypal.me/nolwenndeumie"

[[menu.general]]
name = "Liste des portails"
weight = 10
identifier = "portails"
url = "/portails/"

[[menu.linguistique]]
name = "Général"
weight = 10
identifier = "general"

[[menu.linguistique]]
name = "Le groupe verbal"
weight = 15
identifier = "gv"

[[menu.civilisation]]
name = "History of the United States"
weight = 10
identifier = "us"

[[menu.docs_meta]]
name = "A propos"
weight = 25
identifier = "meta"

[[menu.docs_meta]]
name = "Faire un don"
parent = "meta"
weight = 26
url = "https://paypal.me/nolwenndeumie"

[[menu.docs_meta]]
name = "Code source"
parent = "meta"
weight = 27
url = "https://github.com/NolwennDeumie/linguistique"
