baseURL = "https://nolwenndeumie.github.io/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Linguistique"
theme = "hugo-royal-theme"

[social]
twitter = "iWannaSlytherIn"

[[menu.global]]
name = "Twitter"
weight = 1
identifier = "twitter"
url = "https://twitter.com/IWannaSlytherIn"

[[menu.docs]]
name = "Sommaire"
weight = 10
identifier = "sommaire"

[[menu.docs]]
name = "GitHub"
weight = 15
identifier = "meta"

[[menu.docs]]
name = "Code source"
parent = "meta"
url = "https://github.com/NolwennDeumie/linguistique"
