baseURL = "https://nolwenndeumie.github.io/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Linguistique"
theme = "hugo-royal-theme"

[social]
twitter = "iWannaSlytherIn"

[[menu.global]]
name = "Twitter"
weight = 1
identifier = "twitter"
url = "https://twitter.com/IWannaSlytherIn"

[[menu.docs]]
name = "Général"
weight = 10
identifier = "general"

[[menu.docs]]
name = "Le groupe verbal"
weight = 15
identifier = "gv"

[[menu.docs]]
name = "Le groupe nominal"
weight = 20
identifier = "gn"

[[menu.docs]]
name = "GitHub"
weight = 25
identifier = "meta"

[[menu.docs]]
name = "Code source"
parent = "meta"
url = "https://github.com/NolwennDeumie/linguistique"
